[tool.poetry]
name = "demo"
version = "0.1.0"
description = ""
authors = ["charliechen114514 <725610365@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12 <3.13"
mediapipe = "^0.10.20"
pyside6 = {version = "<6.8.0", source = "tsinghua"}
pygrabber = {version = "^0.2", source = "tsinghua"}


[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
